### ISSUE TITLE
关于配置文件构造和使用缺乏详细说明和示例代码|Lack of Detailed Instructions and Examples for Configuration File Construction and Usage

### ISSUE THREAD

**Issue by Preyou** [kirklin/unplugin-config#1]
文档里只提到了配置文件生成到哪里，没说怎么构造以及使用。

给的示例代码最后跳来跳去，我只找到了文档里列出来的那几个选项，还是不清楚他是根据什么构造的配置文件。

希望作者能给出更详细些的说明

谢谢

**Comment by kirklin** [comment]
我们建议您参考项目的 playground 中的代码示例。在示例代码中，配置文件是根据项目中的 .env 文件构建的。例如，对于 Vite 构建工具，示例代码如下：
```
import { defineConfig } from "vite";
import Inspect from "vite-plugin-inspect";
import Unplugin from "../src/vite";

export default defineConfig({
  plugins: [
    Inspect(),
    Unplugin({
      disabledConfig: false,
      globConfigFileName: "_app.config.js",
      outputDir: "dist",
      appName: "Celeris-Admin",
      envConfigPrefix: "VITE_GLOB_",
    }),
  ],
});
```
https://github.com/kirklin/unplugin-config/blob/main/playground/vite.config.ts
别的构建工具可以参考文档install下面的部分

**Comment by Preyou** [comment]
> 我们建议您参考项目的 playground 中的代码示例。在示例代码中，配置文件是根据项目中的 .env 文件构建的。例如，对于 Vite 构建工具，示例代码如下：
> 
> ```
> import { defineConfig } from "vite";
> import Inspect from "vite-plugin-inspect";
> import Unplugin from "../src/vite";
> 
> export default defineConfig({
>   plugins: [
>     Inspect(),
>     Unplugin({
>       disabledConfig: false,
>       globConfigFileName: "_app.config.js",
>       outputDir: "dist",
>       appName: "Celeris-Admin",
>       envConfigPrefix: "VITE_GLOB_",
>     }),
>   ],
> });
> ```
> 
> https://github.com/kirklin/unplugin-config/blob/main/playground/vite.config.ts 别的构建工具可以参考文档install下面的部分

非常感谢
