### ISSUE TITLE
修改配置项不生效

### ISSUE THREAD

**Issue by holyrong** [kirklin/unplugin-config#2]
### Describe the bug

参考playground中的例子，在vite的build配置中添加以下代码：
 unplugin({
        appName: 'myapp',
        envConfigPrefix: 'VITE_API_',
        outputDir: OUTPUT_DIR,
        disabledConfig: false,
      }),
用vite build之后，修改 _app.config.js中的配置项VITE_API_BASE_URL，部署后，项目运行的还是在.env.production中配置的原始url，根本就没有使用 _app.config.js中修改的url。

请问是不是少了什么配置？还是插件的bug？

### Reproduction

0.0.3

### System Info

```Shell
vue3，vite 3.2.7
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by holyrong** [comment]
@kirklin index.html中也加入了对_app.config.js的引用

**Comment by kirklin** [comment]
能不能提供一个最小化的实现

**Comment by kirklin** [comment]
不过我猜测你的问题是出在生产环境依然读取的是env里面的配置。应该读window上的配置
我觉得你可以参考这个文件https://github.com/kirklin/celeris-web/blob/master/packages/web/utils/src/config.ts
```ts
function getAppGlobalEnvConfig(env: GlobEnvConfig): GlobEnvConfig {
  if (JSON.parse(String(env.VITE_GLOB_BUILD_GENERATE_CONFIG))) {
    const envName = getAppConfigFileName(env);
    return env?.DEV ? env : window[envName];
  }
  return env;
}
```

**Comment by holyrong** [comment]
> 

读的是 .env.production中的配置。

**Comment by holyrong** [comment]
> unplugin({
> appName: 'myapp',
> envConfigPrefix: 'VITE_API_',
> outputDir: OUTPUT_DIR,
> disabledConfig: false,
> }),

我就是在vite中配置了这个插件，然后利用另一个插件将生成的_app.config.js添加到index.html

插件配置的代码：
`unplugin({
appName: 'myapp',
envConfigPrefix: 'VITE_API_',
outputDir: OUTPUT_DIR,
disabledConfig: false,
}),`
编译后，_app.config.js中的VITE_API_BASE_URL中的值与.env.production一致，
部署后，修改_app.config.js中的VITE_API_BASE_URL，不生效，浏览器调试的时候，发现一直调用的是.env.production中的URL地址。（与.env.development中的URL不一样的）

**Comment by holyrong** [comment]
getConfigFileName 方法以及GlobEnvConfig等类型有没有导出？
@kirklin

**Comment by kirklin** [comment]
插件只会帮助你把变量挂到window上，剩下的需要自己处理

**Comment by kirklin** [comment]
在生产环境中通过window[__PRODUCTION__这里是配置项appName填的值__CONF__]来读取配置。
