### ISSUE TITLE
Support for Custom 'env' Directory Configuration | 能否添加一个支持env目录的配置

### ISSUE THREAD

**Issue by MrZT** [kirklin/unplugin-config#4]
### Clear and concise description of the problem

zh: 目前只支持生成在根目录下的.env.*文件变量，如果我改变了.env文件路径，例如放在根目录下的xxx文件夹下(xxx/.env),则会找不到.env文件，从而导致生成失败。
希望支持自定义env文件目录，类似于vite配置中的envDir

en: Currently, the plugin only supports generating environment variables from '.env.*' files located in the root directory. If I change the path of the '.env' file, for example, by placing it in a subdirectory of the root (e.g., 'xxx/.env'), the plugin fails to find the '.env' file, leading to generation failures.

I would like to suggest adding support for a custom 'env' directory, similar to the 'envDir' configuration in Vite.

### Suggested solution

类似于vite配置中的envDir.

Implement a feature similar to Vite's 'envDir' configuration.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kirklin** [comment]
Thanking the mentioning that this feature will be supported starting from version 0.1.0.

**Comment by kirklin** [comment]
```js
const options = {
  appName: "MyApp",
  ...
  envVariables: {
    prefix: "VITE_GLOB_",
    files: [".env.production", ".env"],
  },
};
```
