### ISSUE TITLE
打包警告 以及 baseUrl

### ISSUE THREAD

**Issue by Harrison3098** [kirklin/unplugin-config#5]
### Describe the bug

1. 打包会出现如下警告
![image](https://github.com/kirklin/unplugin-config/assets/112457263/dc53a0d8-6391-48e4-8b80-99c8956ea450)
2. htmlInjection没有baseUrl的配置，无法将`src="/_app.config.js"`修改为其他
![image](https://github.com/kirklin/unplugin-config/assets/112457263/7b6fe7d7-f503-4228-8b70-326273bc0b05)

是不足？还是说有什么是被我忽略的？

### Reproduction

none

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 97.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    npm: 10.2.0 - /usr/local/bin/npm
    pnpm: 8.1.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome Canary: 120.0.6091.0
    Edge: 118.0.2088.69
    Safari: 17.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laizuan** [comment]
![image](https://github.com/kirklin/unplugin-config/assets/27326994/3927fc27-1641-45d7-a8d8-89cbc1cae85c)

**Comment by kirklin** [comment]
感谢反馈，vite环境下打包警告已在0.1.4版本修复，baseDir属性在插件的根目录配置
