### ISSUE TITLE
The plugin isn't use in vite serve model

### ISSUE THREAD

**Issue by mini-blog** [kirklin/unplugin-config#6]
### Clear and concise description of the problem

when using the command `npm run dev`, it doesn't work, tips: http://localhost:8000/_app.config.js status is 404
but the build type is normally

### Suggested solution

We need support serving model running

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kirklin** [comment]
Thanks for the feedback, this will be fixed in version 0.1.5!

**Comment by mini-blog** [comment]
thanks, I watched your source code, When the application is `development` model should implant config code to an HTML file

**Comment by mini-blog** [comment]
Does the plugin only use `build` model?

**Comment by kirklin** [comment]
Yes, this plugin was designed to only work at build time

**Comment by kirklin** [comment]
If you are in a development environment, you should use the variables of the development environment.
https://github.com/kirklin/celeris-web/blob/master/packages/web/utils/src/config.ts
![image](https://github.com/kirklin/unplugin-config/assets/17453452/6b34b56d-b423-4034-8ad4-e3caebd3c436)

**Comment by mini-blog** [comment]
thanks, and I have some advice, on building a config JavaScript file that shouldn't remove space

**Comment by mini-blog** [comment]
user need usually edit it
